### ISSUE TITLE
Suggestions for Improving RedBlackTree Design and API Consistency

### ISSUE THREAD

**Issue by copi143** [plos-clan/libtrees#2]
The template for `RedBlackTree` is `<ValueType, KeyType>`, but the constructor for `RedBlackTree::RBTreeNode` is `(key, value)`, which feels unintuitive.

The `insert` function should accept `(key, value)` rather than `(node)`.

`RBTreeNode` should not be `public`.

The `destroy` function should be `static`.

The functions `swap`, `inorder`, and `is_RBtree` should be `private`.

Since `RBTreeIterator` is defined within `RedBlackTree`, it should not have template parameters.

In line 126, `using iterator = RBTreeIterator< T, T &, T *>;` — type names should start with uppercase letters.

**Comment by SegmentationFaultCD** [comment]
Thank you for your advice, I will modify my code if I have time to do it.
